version: "3.8"
services:
  database:
    container_name: database
    image: neo4j:5.20.0-community
    ports:
      - 7474:7474
      - 7687:7687
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/plugins:/plugins

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.0
    ports:
      - 8080:8080
    command: start-dev
    volumes:
      - ./keycloak-auth/keycloak-data-volume:/opt/keycloak/data/
