version: "3.8"
services:
  database:
    container_name: database
    env_file: .env
    image: neo4j:5.20.0-community
    ports:
      - ${DB_HTTP_PORT}:${DB_HTTP_PORT}
      - ${DB_BOLT_PORT}:${DB_BOLT_PORT}
      # - 7474:7474
      # - 7687:7687
    restart: unless-stopped
    # environment:
    #   - DB_BOLT_PORT=${DB_BOLT_PORT}
    #   - DB_HTTP_PORT=${DB_HTTP_PORT}
    # #   - NEO4J_AUTH=${NEO4J_AUTH}
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins

  keycloak:
    container_name: keycloak
    # env_file: .env
    image: quay.io/keycloak/keycloak:25.0.0
    ports:
      - 8080:8080
    command: start-dev
    environment:
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT=false
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=Haslo123!!!
      - KC_LOG_LEVEL=INFO
    volumes:
      - ./keycloak-auth/keycloak-data-volume:/opt/keycloak/data/
  # backend:
  #   image: node:20-alpine
  #   depends_on:
  #     - database
  #     - keycloak
  #   container_name: backend
  #   # build:
  #   #   context: ./backend
  #   #   dockerfile: Dockerfile
  #   # env_file: ./backend/.env
  #   ports:
  #     - 7000:7000
  #   volumes:
  #     - ./backend:/server
  #   working_dir: /server
  #   command: npm start

  # frontend:
  #   image: node:20-alpine
  #   depends_on:
  #     - backend
  #   container_name: frontend
  #   # build:
  #   #   context: ./frontend
  #   #   dockerfile: Dockerfile
  #   # env_file: ./frontend/.env
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend:/app
  #   working_dir: /app
  #   command: npm run dev

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf

  # nginx:
  #   image: nginx:1.27.0-alpine
  #   container_name: nginx
  #   ports:
  #     # - 8080:8080
  #     - 3001:3001
  #     - 2001:2001
  #     - 7001:7001
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #   depends_on:
  #     - frontend
  #     - keycloak
