version: "3.8"
services:
  db:
    container_name: movie-db
    env_file: .env
    image: neo4j:5.20.0-community
    ports:
      - ${DB_HTTP_PORT}:${DB_HTTP_PORT}
      - ${DB_BOLT_PORT}:${DB_BOLT_PORT}
      # - 7474:7474
      # - 7687:7687
    restart: unless-stopped
    # environment:
    #   - DB_BOLT_PORT=${DB_BOLT_PORT}
    #   - DB_HTTP_PORT=${DB_HTTP_PORT}
    # #   - NEO4J_AUTH=${NEO4J_AUTH}
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins
  keycloak:
    container_name: keycloak-auth
    env_file: .env
    image: quay.io/keycloak/keycloak:25.0.0
    ports:
      - 8080:8080
    command: start-dev
    # environment:
    #   - KEYCLOAK_ADMIN=admin
    #   - KEYCLOAK_ADMIN_PASSWORD=Haslo123!!!
    volumes:
      - ./keycloak-auth/keycloak-data-volume:/opt/keycloak/data/
  # api:
  #   container_name: movie-api
  #   env_file: ./backend/.env
  #   ports:
  #     - "7000:7000"
  #   build: ./backend

  # frontend:
  #   container_name: movie-frontend
  #   env_file: ./frontend/.env
  #   ports:
  #     - "3000:3000"
